name: Web - CD

on:
  push:
    branches:
      - main

env:
  AZURE_STORAGE_ACCOUNT: 'togethersa01'
  NODE_VERSION: '10.x'
  AZURE_WEBAPP_PACKAGE_PATH: './Web/build'
  AZURE_WEBAPP_NAME: 'drawittogether'

defaults:
  run:
    working-directory: ./Web

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: npm install, build
      run: |
        npm install
        npm run build
   
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI Action
      uses: Azure/cli@1.0.4
      with:
        # Specify the script here
        inlineScript: |
          az storage blob upload-batch --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} --destination '$web' --source env.AZURE_WEBAPP_PACKAGE_PATH  

    - name: Publish to Service
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_SERVICE_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'